# Generated by Django 4.0.3 on 2022-03-22 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='teams',
            new_name='team',
        ),
    ]
