# Generated by Django 4.0.3 on 2022-04-17 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactus',
        ),
    ]
