# Generated by Django 4.0.3 on 2022-05-03 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0004_contactus_message_alter_contactus_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='user_id',
        ),
    ]
