# Generated by Django 4.0.3 on 2022-04-17 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_body_style_alter_car_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 17, 22, 40, 59, 850170)),
        ),
    ]
