# Generated by Django 4.0.3 on 2022-06-01 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_banner_alter_car_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 1, 19, 24, 6, 764695)),
        ),
        migrations.AlterField(
            model_name='car',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 1, 19, 24, 6, 764695)),
        ),
    ]
